[project]
name = "clean-bibliography"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bibtexparser>=1.4.3",
    "pandas>=2.3.1",
    "tabulate>=0.9.0",
]
